import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "@/components/navigation/navigation";
import localFont from "next/font/local";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const biotif = localFont({
  src: "../../public/fonts/Biotif-Variable/font.woff2",
  variable: "--biotif",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={biotif.variable}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
